app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    password_secure = db.Column(db.String(255))
    comment = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    blog = db.relationship('Blog',backref = 'user',lazy = "dynamic")
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.password_hash, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'
class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Blog(db.Model):
    __tablename__ = 'blogs'
    id =db.Column(db.Integer,primary_key=True)
    pitch_content =db.Column(db.String())
    pitch_category =db.Column(db.String(255))
    user_id= db.Column(db.Integer,db.ForeignKey('users.id'))


    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blog(cls,id):
        blogs = Blog.query.filter_by(id=id).all()
        return blogs
    @classmethod
    def get_all_blogs(cls):
        blogs =Blog.query.order_by('-id').all()
        return blogs
    @classmethod
    def get_category(cls,cat):
        category =Blog.query.filter_by(blog_category=cat).order_by('-id').all()
        return category

class Comment(db.Model):
   __tablename__ = 'comments'

   id = db.Column(db.Integer, primary_key=True)
   comment_content = db.Column(db.String())
   pitch_id = db.Column(db.Integer)
   user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

   def save_comment(self):
       db.session.add(self)
       db.session.commit()

   @classmethod
   def get_comments(cls, id):
       comments = Comment.query.filter_by(blog_id=id).all()
       return comments



class PhotoProfile(db.Model):
   __tablename__ = 'profile_photos'

   id = db.Column(db.Integer, primary_key=True)
   pic_path = db.Column(db.String())
   user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required

class CommentForm(FlaskForm):
 comment = TextAreaField('Comment title')

 submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class AddBlog(FlaskForm):
    blog = TextAreaField('Write your blog',validators =[Required()])
    category = RadioField('Pick Category',
                            choices=[('political', 'political'),
                                  ('fashion', 'fashion'),
                                     ('vehicle', 'vehicle')],
                            validators=[Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
   category = StringField('Blog category',validators=[Required()])
   content = TextAreaField('Blog', validators=[Required()])

   submit = SubmitField('Submit')
class PostForm(FlaskForm):
    category = StringField('Blog category',validators=[Required()])
    content = TextAreaField('Blog', validators=[Required()])

    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()
def create_app(config_name):
    app = Flask(__name__)


    
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)
    # Registering the blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask_login import login_required, current_user
from flask import render_template,request,redirect,url_for,abort
from ..models import  User,Blog,Comment
from .forms import CommentForm,UpdateProfile,AddBlog,PostForm
from .. import db,photos
from . import main
import markdown2


@main.route('/')
def index():
    return render_template('index.html',title='tasha')

@main.route('/bloged/comment/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm()
    blog = Blog.get_blog(id)
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(blog_id=id, comment_content=comment, user_id=current_user.id)
        new_comment.save_comment()
    comment = Comment.get_comments(id)

    return render_template('new_comment.html', comment_form=form, blog=blog, comment=comment)

@main.route('/bloged', methods=['GET', 'POST'])
def post():
    form = AddBlog()
    if form.validate_on_submit():
        new_blog = Blog(blog_content=form.blog.data,blog_category=form.category.data)
        db.session.add(new_blog)
        db.session.commit()
    blog=Blog.query.all()
    return render_template('bloged.html',form=form, blog=blog)

@main.route('/Fashion', methods=['GET', 'POST'])
def fashion():
    fashion = Blog.query.filter_by(blog_category="fashion").all()
    print(fashion)
    return render_template('fashion.html', blog=fashion)
@main.route('/Political', methods=['GET', 'POST'])
def political():
    political = Blog.query.filter_by(blog_category="political").all()
    print(political)
    return render_template('political.html', blog=political)
@main.route('/Vehicle', methods=['GET', 'POST'])
def vehicle():
    vehicle = Blog.query.filter_by(Blog_category="vehicle").all()
    print(vehicle)
    return render_template('vehicle.html', blog=vehicle)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST','GET'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user_photo = PhotoProfile(pic_path = path,user = user)
        db.session.commit()
    return redirect(url_for('main.update_profile',uname=uname))
@main.route('/fashion', methods=['GET','POST'])
@login_required
def fashion():
   post_form = PostForm()
   if post_form.validate_on_submit():
       user = current_user
       new_post = Blog(title = post_form.title.data,post_content=post_form.post.data,category = post_form.category.data,user = user)
       db.session.add(new_post)
       db.session.commit()
       return redirect(url_for('main.writer_dashboard',PostForm=post_form))
   posts = Blog.query.all()
   return render_template('fashion.html',PostForm=post_form,posts=post)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
  {{super()}}
  <link rel="stylesheet" href="/static/css/styles.css">
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/blog.html
{% import 'macros.html' as macro%}

app/templates/bloged.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- Styles block -->



<!-- Content block -->
{% block content %}
<div class="container">

  {{ wtf.quick_form(form) }}

  <div class="row">

        <h1>/blog</h1>
        <hr>

        {% if blog %}
            {{ macro.displayBlogs(blog) }}

        {% else%}
            <h3 class="text-center">There is no blog </h3>
        {% endif %}

    </div>

</div>
{% endblock %}

app/templates/fashion.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' %}
{% block content %}
{{wtf.quick_quick(PostForm)}}

{% for blog in posts %}
{{blog.pitch_content}}
{% endfor %}
{% endblock %}

app/templates/index.html
<h1>HELLO WELCOME TO MY BLOG</h1>
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Content block -->
{% block content %}

<div class="container">

  {% if current_user.is_authenticated%}
    <h1>Hello {{current_user.username}}</h1>
  {% else %}
    <h1>Hello {{title}}</h1>
  {%endif%}
    <form>
        <input type="text" name="movie_query" placeholder="Search for a Blog" class="form-control">
        <input type="submit"  value="Submit" class="btn btn-default">
    </form>

</div>
{% endblock %}

app/templates/macros.html
{% macro displayBlogs(my_blogs) %}
{% for blog in my_blogs %}
<div class="col-md-12 blogs">

   <p>{{blog.blog_content}}</p>

   <a href="/bloged/comment/{{blog.id}}" <p>comment</p></a>


{% endfor %}
{% endmacro %}

{% macro displayComments(my_comments) %}
{% for comment in my_comments %}

<h2>{{ comment.comment_content }}</h2>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  body {
      font-family: "Lato", sans-serif;
  }
  
  .sidenav {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
  }
  
  .sidenav a {
      padding: 8px 8px 8px 32px;
      text-decoration: none;
      font-size: 25px;
      color: #818181;
      display: block;
      transition: 0.3s;
  }
  
  .sidenav a:hover {
      color: #f1f1f1;
  }
  
  .sidenav .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
  }
  
  @media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
  }
  </style>
  </head>
  <body>
  
  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="#">Vehicles</a>
    <a href="/fashion">Fashion</a>
    <a href="#">Political</a>
  </div>
  <ul class="nav navbar-nav navbar-left">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.update_pic',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
  
  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>
  
  <script>
  function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
  }
  
  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
  }
  </script>
       
  </body>
  </html> 
  

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}
{% block content %}
<div class="container">


  <div class="card">
    <div class="card-body">
      {{ macro.displayBlog(blog) }}
    </div>
  </div>


<div class="col-md-12">
          {{ wtf.quick_form(comment_form) }}
</div>

{{ macro.displayComments(comment) }}
</div>
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}
{% block content %}
<div class="container">


  <div class="card">
    <div class="card-body">
      {{ macro.displayBlogs(blog) }}
    </div>
  </div>


<div class="col-md-12">
          {{ wtf.quick_form(comment_form) }}
</div>

{{ macro.displayComments(comment) }}
</div>
{% endblock %}

app/templates/political.html
{% extends 'base.html'%}
{% block content %}
{% for blog in blog %}
{{blog.blog_content}}
{% endfor %}
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
     {% if user.profile_pic_path %}

     <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

     {%else%}
     <p>No profile picture</p>

     {% endif %}

         {% if user == current_user %}

     <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

       <input type="file"  name="photo" class="form-control" required>
       <input type="submit">
     </form>
       {% endif %}
   </div>
</div>
{% for blog in blog %}
{{blog.blog_content}}
{% endfor %}

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ blogs| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayBlogList(blog)}}
            </ul>

        </div>

    </div>
{% endblock %}

app/templates/vehicles.html
{% extends 'base.html'%}
{% block content %}
{% for blog in blog %}
{{blog.blog_content}}
{% endfor %}
{% endblock %}